# Generated by Django 3.2 on 2021-07-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210709_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
