# Generated by Django 3.2 on 2021-07-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_exam_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_released',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
