# Generated by Django 3.2 on 2021-07-22 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_exam_is_released'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='20991231Q9999', max_length=25)),
                ('institute_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('level_code', models.CharField(default='NA', max_length=5)),
                ('subject_code', models.CharField(default='NA', max_length=5)),
                ('particulars', models.CharField(default='Question Particulars', max_length=250)),
                ('status', models.IntegerField(default=1)),
                ('status_desc', models.CharField(default='Status Description', max_length=50)),
                ('image_path', models.ImageField(default='', upload_to='question')),
                ('type', models.IntegerField(default=1)),
                ('answer', models.CharField(default='Answer for Reference', max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2021, 10, 20)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2021, 7, 22)),
        ),
    ]
