# Generated by Django 3.2 on 2021-07-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20210722_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status_desc',
            field=models.CharField(default='This is active question', max_length=50),
        ),
    ]
