# Generated by Django 3.2 on 2021-07-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_question_status_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euid', models.CharField(default='20991231E9999', max_length=25)),
                ('quid', models.CharField(default='20991231Q9999', max_length=25)),
                ('institute_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quid', models.CharField(default='20991231Q9999', max_length=25)),
                ('tag', models.CharField(default='X', max_length=1)),
                ('particulars', models.CharField(default='Question Option Particulars', max_length=250)),
                ('is_correct', models.IntegerField(default=0)),
            ],
        ),
    ]
