# Generated by Django 3.2 on 2021-07-25 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_exam_question_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_options',
            name='institute_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question_options',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2021, 10, 23)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2021, 7, 25)),
        ),
    ]
