# Generated by Django 3.2 on 2021-08-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20210802_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='section_code',
            field=models.CharField(default='NA', max_length=5),
        ),
    ]
