# Generated by Django 3.2 on 2021-08-08 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_exam_section_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='source',
            field=models.CharField(default='NA', max_length=25),
        ),
        migrations.AddField(
            model_name='exam',
            name='source_uid',
            field=models.CharField(default='20991231E9999', max_length=25),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2021, 11, 6)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2021, 8, 8)),
        ),
    ]
