# Generated by Django 3.2 on 2021-08-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_auto_20210808_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='exam',
            name='source',
            field=models.CharField(default='NA', max_length=5),
        ),
    ]
