# Generated by Django 3.2 on 2021-08-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_auto_20210808_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='source',
            new_name='source_code',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='type',
            new_name='type_code',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='type_code',
        ),
        migrations.AddField(
            model_name='exam',
            name='source_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='type_desc',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='type_desc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
