# Generated by Django 3.2 on 2021-08-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_auto_20210808_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type_code',
            new_name='type',
        ),
    ]
