# Generated by Django 3.2 on 2021-08-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_rename_type_code_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_released',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
