# Generated by Django 3.2 on 2021-08-13 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_alter_exam_is_released'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('subject_id', models.CharField(default='NA', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='question_marks',
            name='subject_id',
            field=models.CharField(default='NA', max_length=5),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2021, 11, 11)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2021, 8, 13)),
        ),
    ]
