# Generated by Django 3.2 on 2021-08-17 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_auto_20210815_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2021, 11, 15)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2021, 8, 17)),
        ),
    ]
