# Generated by Django 3.2 on 2021-08-17 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_auto_20210817_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='institute_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 20, 59, 48, 315500)),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 20, 59, 48, 315500)),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 20, 59, 48, 315500)),
        ),
        migrations.AddField(
            model_name='question_marks',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 20, 59, 48, 314485)),
        ),
        migrations.AddField(
            model_name='question_options',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 20, 59, 48, 314485)),
        ),
    ]
