# Generated by Django 3.2 on 2021-08-31 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0029_auto_20210831_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXAM_ATTENDENCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euid', models.CharField(default='20991231E9999', max_length=25)),
                ('institute_id', models.IntegerField(default=0)),
                ('level_code', models.CharField(default='NA', max_length=5)),
                ('subject_code', models.CharField(default='NA', max_length=5)),
                ('section_code', models.CharField(default='NA', max_length=5)),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2021, 8, 31, 21, 10, 51, 219762))),
                ('student_id', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 8, 31, 21, 10, 51, 219762))),
                ('attend_status', models.CharField(default='N', max_length=5)),
                ('attend_status_desc', models.CharField(default='Not Yet Attended By Student', max_length=100)),
                ('sch_start_date', models.DateTimeField(default=datetime.date(2021, 8, 31))),
                ('sch_end_date', models.DateTimeField(default=datetime.date(2021, 11, 29))),
                ('full_marks', models.IntegerField(default=0)),
                ('scored_marks', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_attended_questions', models.IntegerField(default=0)),
                ('exam_attend_date', models.DateTimeField(default='2020-01-01 00:00:00')),
                ('exam_completion_date', models.DateTimeField(default='2020-01-01 00:00:00')),
            ],
        ),
        migrations.CreateModel(
            name='EXAM_RELEASED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euid', models.CharField(default='20991231E9999', max_length=25)),
                ('institute_id', models.IntegerField(default=0)),
                ('level_code', models.CharField(default='NA', max_length=5)),
                ('subject_code', models.CharField(default='NA', max_length=5)),
                ('section_code', models.CharField(default='NA', max_length=5)),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2021, 8, 31, 21, 10, 51, 219762))),
                ('released_by', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 8, 31, 21, 10, 51, 219762))),
                ('sch_start_date', models.DateTimeField(default=datetime.date(2021, 8, 31))),
                ('sch_end_date', models.DateTimeField(default=datetime.date(2021, 11, 29))),
                ('full_marks', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('status', models.CharField(default='OPEN', max_length=25)),
                ('status_desc', models.CharField(default='Released Exam - Open To Participate', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 21, 10, 51, 219762)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 21, 10, 51, 219762)),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 21, 10, 51, 219762)),
        ),
        migrations.AlterField(
            model_name='question_marks',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 21, 10, 51, 219762)),
        ),
        migrations.AlterField(
            model_name='question_options',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 21, 10, 51, 219762)),
        ),
    ]
