# Generated by Django 3.2 on 2021-09-16 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0030_auto_20210831_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 37, 7, 381496)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2021, 12, 15)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2021, 9, 16)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 37, 7, 381496)),
        ),
        migrations.AlterField(
            model_name='exam_attendence',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 37, 7, 379495)),
        ),
        migrations.AlterField(
            model_name='exam_attendence',
            name='sch_end_date',
            field=models.DateTimeField(default=datetime.date(2021, 12, 15)),
        ),
        migrations.AlterField(
            model_name='exam_attendence',
            name='sch_start_date',
            field=models.DateTimeField(default=datetime.date(2021, 9, 16)),
        ),
        migrations.AlterField(
            model_name='exam_attendence',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 37, 7, 379495)),
        ),
        migrations.AlterField(
            model_name='exam_released',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 37, 7, 380484)),
        ),
        migrations.AlterField(
            model_name='exam_released',
            name='sch_end_date',
            field=models.DateTimeField(default=datetime.date(2021, 12, 15)),
        ),
        migrations.AlterField(
            model_name='exam_released',
            name='sch_start_date',
            field=models.DateTimeField(default=datetime.date(2021, 9, 16)),
        ),
        migrations.AlterField(
            model_name='exam_released',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 37, 7, 380484)),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 37, 7, 381496)),
        ),
        migrations.AlterField(
            model_name='question_marks',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 37, 7, 380484)),
        ),
        migrations.AlterField(
            model_name='question_options',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 37, 7, 380484)),
        ),
    ]
