# Generated by Django 3.2 on 2021-09-16 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0031_auto_20210916_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_released',
            name='IS_PROCESSED_BY_AUTO_SCRIPT',
            field=models.CharField(default='NA', max_length=5),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 19, 33, 28, 506445)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 19, 33, 28, 506445)),
        ),
        migrations.AlterField(
            model_name='exam_attendence',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 19, 33, 28, 504409)),
        ),
        migrations.AlterField(
            model_name='exam_attendence',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 19, 33, 28, 504409)),
        ),
        migrations.AlterField(
            model_name='exam_released',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 19, 33, 28, 505444)),
        ),
        migrations.AlterField(
            model_name='exam_released',
            name='status_desc',
            field=models.CharField(default='Released Exam - Open To Participant', max_length=100),
        ),
        migrations.AlterField(
            model_name='exam_released',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 19, 33, 28, 504409)),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 19, 33, 28, 506445)),
        ),
        migrations.AlterField(
            model_name='question_marks',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 19, 33, 28, 505444)),
        ),
        migrations.AlterField(
            model_name='question_options',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 19, 33, 28, 505444)),
        ),
    ]
