# Generated by Django 3.2 on 2021-09-21 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0034_auto_20210917_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 10, 4, 9, 982373)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2021, 12, 20)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2021, 9, 21)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 10, 4, 9, 982373)),
        ),
        migrations.AlterField(
            model_name='exam_attendence',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 10, 4, 9, 982373)),
        ),
        migrations.AlterField(
            model_name='exam_attendence',
            name='sch_end_date',
            field=models.DateTimeField(default=datetime.date(2021, 12, 20)),
        ),
        migrations.AlterField(
            model_name='exam_attendence',
            name='sch_start_date',
            field=models.DateTimeField(default=datetime.date(2021, 9, 21)),
        ),
        migrations.AlterField(
            model_name='exam_attendence',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 10, 4, 9, 982373)),
        ),
        migrations.AlterField(
            model_name='exam_released',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 10, 4, 9, 982373)),
        ),
        migrations.AlterField(
            model_name='exam_released',
            name='is_processed_by_script',
            field=models.CharField(default='NO', max_length=5),
        ),
        migrations.AlterField(
            model_name='exam_released',
            name='sch_end_date',
            field=models.DateTimeField(default=datetime.date(2021, 12, 20)),
        ),
        migrations.AlterField(
            model_name='exam_released',
            name='sch_start_date',
            field=models.DateTimeField(default=datetime.date(2021, 9, 21)),
        ),
        migrations.AlterField(
            model_name='exam_released',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 10, 4, 9, 982373)),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 10, 4, 9, 982373)),
        ),
        migrations.AlterField(
            model_name='question_marks',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 10, 4, 9, 982373)),
        ),
        migrations.AlterField(
            model_name='question_options',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 10, 4, 9, 982373)),
        ),
    ]
