#-----Global Variable----


EXAM_RELEASED_STATUS_OPEN='OPEN'
EXAM_RELEASED_STATUS_OPEN_DESC='New Released Exam To Students'
EXAM_RELEASED_STATUS_CLOSE='CLOSED'
EXAM_RELEASED_STATUS_CLOSE_DESC='Exam Is Expired'
YES='Y'
NO='N'
SCRIPT_NAME='AUTO_DB_UPDATES'
SCRIPT_NAME_DESC='Update Required Tables'
SCRIPT_EXECUTION_MODE_MANUAL='MANUAL'
SCRIPT_EXECUTION_MODE_AUTO='AUTOMATIC'
EXAM_ATTENDENCE_STATUS_DESC_NO='NOT ATTENDED'
EXAM_ATTENDENCE_ENTRY_SOURCE_ADMIN='ADMIN:STUDENT LEVEL & SECTION ADDITION'
EXAM_ATTENDENCE_ENTRY_SOURCE_TEACHER='TEACHER:EXAM RELEASED'