# Generated by Django 3.2 on 2021-06-16 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_registerinstitute_institute_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('institute_owner', models.CharField(max_length=100)),
                ('institute_contact1', models.CharField(max_length=100)),
                ('institute_contact2', models.CharField(default='N/A', max_length=100)),
                ('institute_email', models.EmailField(max_length=254)),
                ('institute_country', models.CharField(max_length=100)),
                ('institute_state', models.CharField(max_length=100)),
                ('institute_city', models.CharField(max_length=100)),
                ('institute_address', models.CharField(max_length=250)),
                ('institute_pin_code', models.IntegerField(default=100100)),
                ('institute_status', models.CharField(default='Active', max_length=25)),
                ('institute_created_date', models.DateTimeField(default=datetime.date(2021, 6, 16))),
                ('institute_expiry_date', models.DateTimeField(default=datetime.date(2021, 9, 14))),
                ('institute_remarks', models.CharField(default='New Registration', max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterInstitute',
        ),
    ]
