# Generated by Django 3.2 on 2021-06-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210618_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute_user',
            name='address',
            field=models.CharField(default='N/A', max_length=250),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='contact1',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='verify_id',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
