# Generated by Django 3.2 on 2021-06-29 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210619_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='institute_logo_path',
            field=models.ImageField(default='', upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_created_date',
            field=models.DateTimeField(default=datetime.date(2021, 6, 29)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_expiry_date',
            field=models.DateTimeField(default=datetime.date(2021, 9, 27)),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='account_expiry_date',
            field=models.DateTimeField(default=datetime.date(2022, 6, 29)),
        ),
    ]
