# Generated by Django 3.2 on 2021-07-09 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210708_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_UID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='NA', max_length=20)),
                ('table_code', models.CharField(default='NA', max_length=5)),
                ('table', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_created_date',
            field=models.DateTimeField(default=datetime.date(2021, 7, 9)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_expiry_date',
            field=models.DateTimeField(default=datetime.date(2021, 10, 7)),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='account_expiry_date',
            field=models.DateTimeField(default=datetime.date(2022, 7, 9)),
        ),
    ]
