# Generated by Django 3.2 on 2021-07-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210709_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ref_uid',
            old_name='table',
            new_name='table_name',
        ),
    ]
