# Generated by Django 3.2 on 2021-08-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210808_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Exam_Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='NA', max_length=5)),
                ('source', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Exam_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='NA', max_length=5)),
                ('schedule', models.CharField(default='NA', max_length=100)),
            ],
        ),
    ]
