# Generated by Django 3.2 on 2021-08-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_ref_exam_source_ref_exam_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ref_Exam_Source',
        ),
        migrations.DeleteModel(
            name='Ref_Exam_Type',
        ),
    ]
