# Generated by Django 3.2 on 2021-08-18 08:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0023_auto_20210818_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute_user',
            name='account_expiry_date',
        ),
        migrations.RemoveField(
            model_name='institute_user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='institute_user',
            name='contact1',
        ),
        migrations.RemoveField(
            model_name='institute_user',
            name='contact2',
        ),
        migrations.RemoveField(
            model_name='institute_user',
            name='profile_pic_path',
        ),
        migrations.RemoveField(
            model_name='institute_user',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='institute_user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='institute_user',
            name='type',
        ),
        migrations.RemoveField(
            model_name='institute_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='institute_user',
            name='verification_id',
        ),
        migrations.RemoveField(
            model_name='institute_user',
            name='verification_id_type',
        ),
        migrations.AddField(
            model_name='institute_user',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 13, 52, 59, 137388)),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 13, 52, 59, 137388)),
        ),
        migrations.CreateModel(
            name='User_Extra_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact1', models.CharField(default='N/A', max_length=100)),
                ('contact2', models.CharField(blank=True, default='N/A', max_length=100)),
                ('account_expiry_date', models.DateTimeField(default=datetime.date(2022, 8, 18))),
                ('remarks', models.CharField(default='New Individual Registration', max_length=250)),
                ('type', models.CharField(default='N/A', max_length=25)),
                ('verification_id_type', models.CharField(default='N/A', max_length=25)),
                ('verification_id', models.CharField(default='N/A', max_length=25)),
                ('address', models.CharField(default='N/A', max_length=250)),
                ('profile_pic_path', models.ImageField(default='', upload_to='profile')),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2021, 8, 18, 13, 52, 59, 137388))),
                ('status', models.CharField(default='N/A', max_length=25)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
