# Generated by Django 3.2 on 2021-08-19 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210818_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='institute_created_date',
            field=models.DateTimeField(default=datetime.date(2021, 8, 19)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_expiry_date',
            field=models.DateTimeField(default=datetime.date(2021, 11, 17)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_status',
            field=models.CharField(default='InActive', max_length=25),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 14, 33, 5, 130985)),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 14, 33, 5, 130985)),
        ),
        migrations.AlterField(
            model_name='user_extra_info',
            name='account_expiry_date',
            field=models.DateTimeField(default=datetime.date(2022, 8, 19)),
        ),
        migrations.AlterField(
            model_name='user_extra_info',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 14, 33, 5, 130985)),
        ),
    ]
