# Generated by Django 3.2 on 2021-08-31 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20210819_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute_user',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 17, 19, 2, 638432)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_created_date',
            field=models.DateTimeField(default=datetime.date(2021, 8, 31)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_expiry_date',
            field=models.DateTimeField(default=datetime.date(2021, 11, 29)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 17, 19, 2, 638432)),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 17, 19, 2, 638432)),
        ),
        migrations.AlterField(
            model_name='user_extra_info',
            name='account_expiry_date',
            field=models.DateTimeField(default=datetime.date(2022, 8, 31)),
        ),
        migrations.AlterField(
            model_name='user_extra_info',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 17, 19, 2, 638432)),
        ),
    ]
