# Generated by Django 3.2 on 2021-08-31 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210831_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='institute_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 17, 20, 8, 593927)),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 17, 20, 8, 593927)),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 17, 20, 8, 593927)),
        ),
        migrations.AlterField(
            model_name='user_extra_info',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 17, 20, 8, 593927)),
        ),
    ]
