# Generated by Django 3.2 on 2021-09-16 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210831_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automated_Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(default='N/A', max_length=100)),
                ('script_name_desc', models.CharField(default='N/A', max_length=100)),
                ('script_execution_date', models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 37, 7, 367503))),
                ('script_execution_mode', models.CharField(default='N/A', max_length=100)),
                ('script_action', models.CharField(default='N/A', max_length=100)),
                ('script_execution_status', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_created_date',
            field=models.DateTimeField(default=datetime.date(2021, 9, 16)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_expiry_date',
            field=models.DateTimeField(default=datetime.date(2021, 12, 15)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 37, 7, 367503)),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 37, 7, 369504)),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 37, 7, 369504)),
        ),
        migrations.AlterField(
            model_name='user_extra_info',
            name='account_expiry_date',
            field=models.DateTimeField(default=datetime.date(2022, 9, 16)),
        ),
        migrations.AlterField(
            model_name='user_extra_info',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 37, 7, 368493)),
        ),
    ]
