# Generated by Django 3.2 on 2021-09-16 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20210916_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automated_script',
            name='script_execution_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 19, 34, 23, 383324)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 19, 34, 23, 383324)),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 19, 34, 23, 384312)),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 19, 34, 23, 384312)),
        ),
        migrations.AlterField(
            model_name='user_extra_info',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 19, 34, 23, 384312)),
        ),
    ]
