# Generated by Django 3.2 on 2021-09-21 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20210921_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automated_script',
            name='script_execution_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 13, 8, 48, 537953)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 13, 8, 48, 538975)),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 13, 8, 48, 538975)),
        ),
        migrations.AlterField(
            model_name='institute_user',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 13, 8, 48, 538975)),
        ),
        migrations.AlterField(
            model_name='user_extra_info',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 13, 8, 48, 538975)),
        ),
    ]
