# Generated by Django 3.2 on 2021-08-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('level_id', models.CharField(default='NA', max_length=5)),
                ('subject_id', models.CharField(default='NA', max_length=5)),
            ],
        ),
    ]
