# Generated by Django 3.2 on 2021-08-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='subject_id',
            new_name='section_id',
        ),
    ]
