# Generated by Django 3.2 on 2021-08-17 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_subject_id_department_section_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='institute_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 20, 59, 48, 327319)),
        ),
    ]
