# Generated by Django 3.2 on 2021-08-31 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_department_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 17, 20, 8, 593927)),
        ),
    ]
